"""Increase phone column size for volunteers

Revision ID: 115a9769f4c0
Revises: 8eec05a724df
Create Date: 2025-02-07 06:04:19.892437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115a9769f4c0'
down_revision = '8eec05a724df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.alter_column('contact_phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
